name: nimble_survey_app
description: "Nimble Survey app project implemented in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any

  # Network
  dio: ^5.8.0+1
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0

  # Authentication
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^9.2.4

  # Navigation
  go_router: ^15.1.2

  # Riverpod
  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15

  # Misc
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  dart_style: ^3.0.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  # Network
  json_serializable: ^6.9.5

  # Linting
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.15

  # Generator
  retrofit_generator: ^9.2.0
  riverpod_generator: ^3.0.0-dev.15


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.dev
    - .env.staging
    - .env.prod
    - assets/
    - assets/images/
    - assets/lotties/
  fonts:
    - family: Neuzeit
      fonts:
        - asset: assets/fonts/Neuzeit-Regular.otf
          weight: 400
        - asset: assets/fonts/Neuzeit-Bold.otf
          weight: 800
