name: nimble_survey_app
description: "Nimble Survey app project implemented in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.5.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Network
  dio: ^5.8.0+1
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0

  # Authentication
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^9.2.4

  # Navigation
  go_router: ^15.1.2

  # Riverpod
  flutter_riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15

  # Model
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0

  # Environment
  flutter_dotenv: ^5.2.1

  # Test
  mocktail: ^1.0.4

  # Files and images
  file: ^7.0.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  lottie: ^3.3.1

  # Misc
  flutter_local_notifications: ^19.4.0
  fluttertoast: ^8.2.12
  shimmer_animation: ^2.2.2
  dart_style: ^3.0.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.2.1
  wheel_picker: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

  # Network
  json_serializable: ^6.9.5

  # Linting
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.15

  # Generator
  retrofit_generator: ^9.2.0
  riverpod_generator: ^3.0.0-dev.15
  drift_dev: ^2.27.0
  freezed: ^3.0.6

flutter_gen:
  integrations:
    image: true
    flutter_svg: true
    lottie: true
  assets:
    exclude:
      - .env.dev
      - .env.staging
      - .env.prod
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.dev
    - .env.staging
    - .env.prod
    - assets/fonts/
    - assets/images/
    - assets/lotties/
    - assets/color/
    - integration_test/common/assets/mock_network_image.png
  fonts:
    - family: Neuzeit
      fonts:
        - asset: assets/fonts/Neuzeit-Regular.otf
          weight: 400
        - asset: assets/fonts/Neuzeit-Bold.otf
          weight: 800
