name: Create release pull request

on:
  workflow_dispatch:
    inputs:
      release_milestone_url:
        description: Release milestone URL
        required: true
      newVersion:
        description: "Version name"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release_pull_request:
    name: Create release pull request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Find HEAD commit
        id: head
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Build changelog on "master"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          configuration: ".github/workflows/configs/changelog-config.json"
          outputFile: changelog.txt
          # List PRs from the last tag to the HEAD commit
          toTag: ${{ steps.head.outputs.sha }}

      - name: Prepend Release URL into changelog
        shell: bash
        run: |
          echo -e "${{ inputs.release_milestone_url }}\n$(cat changelog.txt)" > changelog.txt

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: release/${{ github.event.inputs.newVersion }}

      - name: Create pull request
        run: |
          gh pr create \
            --draft \
            --base master \
            --head release/${{ github.event.inputs.newVersion }} \
            --title 'Release - ${{ github.event.inputs.newVersion }}' \
            --body-file changelog.txt \
            --label 'type: release' \
            --milestone ${{ github.event.inputs.newVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
