name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g., 1.2.3)'
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update pubspec.yaml version
        run: |
          sed -i "s/^version: .*/version: ${{ github.event.inputs.version }}/" pubspec.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: bump version to ${{ github.event.inputs.version }}"
          title: "chore: bump version to ${{ github.event.inputs.version }}"
          body: "This PR bumps the version to `${{ github.event.inputs.version }}`."
          branch: chore/bump-version-${{ github.event.inputs.version }}
          base: develop
          labels: |
            type: chore
