name: Deploy Staging

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Inject .env files
        run: |
          echo "API_ENDPOINT=${{ secrets.API_ENDPOINT }}" >> .env.staging
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env.staging
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env.staging
          echo "" >> .env.dev
          echo "" >> .env.prod

      - name: Generate Flutter files
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --flavor staging --release --build-number $GITHUB_RUN_NUMBER --dart-define=FLAVOR=staging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: staging-release-apk
          path: build/app/outputs/flutter-apk/app-staging-release.apk

      - name: Upload Android APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_STAGING }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: tester
          releaseNotes: Staging build
          file: build/app/outputs/flutter-apk/app-staging-release.apk
